import pandas as pd
import matplotlib.pyplot as plt
data = [
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
    {"Comment": "I love this product!", "Review": "Positive", "Date": "2023-08-01"},
    {"Comment": "Terrible experience.", "Review": "Negative", "Date": "2020-07-02"},
    {"Comment": "Gret Product", "Review": "Positive", "Date": "2021-01-23"},
    {"Comment": "Nice.....!", "Review": "Positive", "Date": "2019-06-02"},
    {"Comment": "Best quality....", "Review": "Positive", "Date": "2021-10-05"},
    {"Comment": "Better", "Review": "Positive", "Date": "2022-11-12"},
    {"Comment": "Not reachable to my estimation", "Review": "Negative", "Date": "2022-04-22"},
    {"Comment": "Some better", "Review": "Negative", "Date": "2023-05-21"},
    {"Comment": "Okey", "Review": "Neutral", "Date": "2018-06-04"},
    {"Comment": "Need best", "Review": "Neutral", "Date": "2023-06-02"},
]
df = pd.DataFrame(data)
sentiment_counts = df['Review'].value_counts()
plt.bar(sentiment_counts.index, sentiment_counts.values, color=['green', 'red', 'gray'])
plt.xlabel('Review')
plt.ylabel('Count')
plt.title('Distribution')
plt.show()
